config/routes.rb
Rails.application.routes.draw do
  root 'collections#index'

  concern :votable do
    resources :votes, only: [:create, :destroy]
  end

  resources :collections do
    resources :collection_items
  end

  resources :movies do
    concerns :votable
  end

  devise_for :users
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :collection_items
  belongs_to :user

  validates :name, presence: true
  validates :description, length: { maximum: 300 }
  validates :user, presence: true
end

app/models/collection_item.rb
class CollectionItem < ActiveRecord::Base
  belongs_to :collection
  belongs_to :collectible, polymorphic: true

  validates :collection, presence: true
  validates :collectible, presence: true

  delegate :user, to: :collection
end

app/models/concerns/votable.rb
module Votable
  extend ActiveSupport::Concern

  included do
    has_many :votes, as: :votable
  end

  def score
    votes.sum
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  include Votable

  validates :title, presence: true

  def self.search(search_params)
    search_strategy = MovieSearch::MixedSearch.new
    search_strategy.search(search_params)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :collections
  has_many :collection_items, through: :collections
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :votable, polymorphic: true

  validates :user, presence: true
  validates :votable, presence: true
  validates :value, presence: true, inclusion: [-1, 1]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/collection_items_controller.rb
class CollectionItemsController < ApplicationController
  before_action :set_collection
  before_action :set_collection_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @collection_items = @collection.collection_items.all
  end

  def show
  end

  def new
    @collection_item = @collection.collection_items.new
  end

  def edit
  end

  def create
    @collection_item = @collection.collection_items.build(collection_item_params)

    respond_to do |format|
      if @collection_item.save
        format.html { redirect_to [@collection, @collection_item], notice: 'Collection item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @collection_item.update(collection_item_params)
        format.html { redirect_to [@collection, @collection_item], notice: 'Collection item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @collection_item.destroy
    respond_to do |format|
      format.html { redirect_to collection_items_url, notice: 'Collection item was successfully destroyed.' }
    end
  end

  private

  def set_collection
    @collection = current_user.collections.find(params[:collection_id])
  end

  def set_collection_item
    @collection_item = @collection.collection_items.find(params[:id])
  end

  def collection_item_params
    params.require(:collection_item).permit(:collectible_id, :collectible_type)
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @collections = Collection.all
  end

  def show
  end

  def new
    @collection = Collection.new
  end

  def edit
  end

  def create
    @collection = current_user.collections.build(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
    end
  end

  private

  def set_collection
    @collection = current_user.collections.find(params[:id])
  end

  def collection_params
    params.require(:collection).permit(:name, :description)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    if params[:search].present?
      @movies = Movie.search(search_params).order(:title)
    else
      @movies = Movie.all
    end
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def edit
  end


  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
    end
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :year, :genre, :country)
  end

  def search_params
    params.require(:search).permit(:title)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/collection_items/_form.html.haml
= form_for [@collection, @collection_item], html: { class: "form-horizontal", role: "form" } do |f|
  -if @collection_item.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@collection_item.errors.count, "error")} prohibited this collection_item from being saved:"

      %ul
        - @collection_item.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :collectible, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :collectible, class: 'form-control'
  .form-group
    = f.label :collectible_type, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :collectible_type, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/collection_items/edit.html.haml
.page-header
  = link_to collection_items_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @collection_item, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing collection_item

= render 'form'

app/views/collection_items/index.html.haml
.page-header
  = link_to new_collection_collection_item_path(@collection), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Collection item
  %h1 Listing collection_items

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Collection
        %th Collectible
        %th Collectible type
        %th
        %th
        %th

    %tbody
      - @collection_items.each do |collection_item|
        %tr
          %td= collection_item.collection
          %td= collection_item.collectible
          %td= collection_item.collectible_type
          %td= link_to 'Show', collection_item
          %td= link_to 'Edit', edit_collection_item_path(collection_item)
          %td= link_to 'Destroy', collection_item, data: { confirm: 'Are you sure?' }, method: :delete

app/views/collection_items/new.html.haml
.page-header
  = link_to new_collection_collection_item_path(@collection), class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New collection_item

= render 'form'

app/views/collection_items/show.html.haml
.page-header
  = link_to collection_items_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_collection_item_path(@collection_item), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show collection_item

%dl.dl-horizontal
  %dt Collection:
  %dd= @collection_item.collection
  %dt Collectible:
  %dd= @collection_item.collectible
  %dt Collectible type:
  %dd= @collection_item.collectible_type

app/views/collections/_form.html.haml
= form_for @collection, html: { class: "form-horizontal", role: "form" } do |f|
  -if @collection.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@collection.errors.count, "error")} prohibited this collection from being saved:"

      %ul
        - @collection.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :description, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :description, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/collections/edit.html.haml
.page-header
  = link_to collections_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @collection, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing collection

= render 'form'

app/views/collections/index.html.haml
.page-header
  = link_to new_collection_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Collection
  %h1 Listing collections

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Description
        %th
        %th
        %th

    %tbody
      - @collections.each do |collection|
        %tr
          %td= collection.name
          %td= collection.description
          %td= link_to 'Show', collection
          %td= link_to 'Edit', edit_collection_path(collection)
          %td= link_to 'Destroy', collection, data: { confirm: 'Are you sure?' }, method: :delete

app/views/collections/new.html.haml
.page-header
  = link_to collections_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New collection

= render 'form'

app/views/collections/show.html.haml
.page-header
  = link_to collections_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_collection_path(@collection), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show collection

%dl.dl-horizontal
  %dt Name:
  %dd= @collection.name
  %dt Description:
  %dd= @collection.description

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title Collection manager

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Collection manager", "#", class: "navbar-brand"
        #navbar.collapse.navbar-collapse
          - if user_signed_in?
            %ul.nav.navbar-nav
              %li.active
                %a{href: "#"} Home
              %li
                %a{href: "#about"} About
              %li
                %a{href: "#contact"} Contact

            %ul.nav.navbar-nav.navbar-right
              %li= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-btn"
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/movies/_form.html.haml
= form_for @movie, html: { class: "form-horizontal", role: "form" } do |f|
  -if @movie.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@movie.errors.count, "error")} prohibited this movie from being saved:"

      %ul
        - @movie.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :year, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :year, class: 'form-control'
  .form-group
    = f.label :genre, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :genre, class: 'form-control'
  .form-group
    = f.label :country, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :country, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/movies/edit.html.haml
.page-header
  = link_to movies_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @movie, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing movie

= render 'form'

app/views/movies/index.html.haml
.page-header
  = link_to new_movie_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Movie
  %h1 Listing movies

.row
  = form_for :search, url: movies_path, method: :get, html: { class: "form-group" } do |f|
    .input-group
      = f.text_field :title, value: (params[:search][:title] if params[:search]), placeholder: "Search Movies", class: "form-control"
      .input-group-btn
        = button_tag type: :submit, class: "btn btn-default" do
          %span.glyphicon.glyphicon-search

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Title
        %th Year
        %th Genre
        %th Country
        %th
        %th
        %th

    %tbody
      - @movies.each do |movie|
        %tr
          %td= movie.title
          %td= movie.year
          %td= movie.genre
          %td= movie.country
          %td= link_to 'Show', movie
          %td= link_to 'Edit', edit_movie_path(movie)
          %td= link_to 'Destroy', movie, data: { confirm: 'Are you sure?' }, method: :delete

app/views/movies/new.html.haml
.page-header
  = link_to movies_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New movie

= render 'form'

app/views/movies/show.html.haml
.page-header
  = link_to movies_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_movie_path(@movie), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show movie

%dl.dl-horizontal
  %dt Title:
  %dd= @movie.title
  %dt Year:
  %dd= @movie.year
  %dt Genre:
  %dd= @movie.genre
  %dt Country:
  %dd= @movie.country